version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image:
      app-python-flask
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:oliver@db:5433/Actividad8
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oliver
      POSTGRES_DB: Actividad8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
